# configs/selectors.yaml
# Each top‑level key is a campaign name.

faculty_directory:
  list_page:
    link_selectors:
      - css: ".faculty-list a.profile-link"
      - xpath: "//div[@class='faculty']//a[contains(@href,'/profile/')]"
    pagination:
      next_css: "a.next"
      next_xpath: "//a[@rel='next']"
      next_url_regex: "\\?page=\\d+$"

default:
  list_page:
    link_selectors:
      - css: ".gallery-item a"
  profile_page:
    fields: &default_fields
      name:
        - css: "h1.title"
        - xpath: "//h1[contains(@class,'title')]"
      email:
        - css: "a.email"
        - xpath: "//a[contains(@href,'mailto:')]"
      phone:
        - css: ".contact .phone"
      socials:
        - css: ".social-links a"
      title:
        - css: ".bio h2"
      organization:
        - css: ".bio .company"

generic_business:
  list_page:
    link_selectors:
      - css: ".business-card a.details"
    pagination:
      next_css: "a[rel='next']"
  profile_page:
    fields:
      name:
        - css: ".profile-header h1"
      email:
        - css: ".contact-info a[href^='mailto:']"
      phone:
        - css: ".contact-info .phone"
      socials:
        - css: ".social-icons a"
      title:
        - css: ".profile-header .role"
      organization:
        - css: ".profile-header .company"

wedding_planner:
  list_page:
    link_selectors:
      - css: ".gallery-item a"
    pagination:
      next_css: ".pagination .next"
  profile_page:
    fields: *default_fields

gallery_curator:
  list_page:
    link_selectors:
      - css: ".gallery-item a"
    pagination:
      next_css: ".pagination .next"
  profile_page:
    fields: *default_fields

collaborator:
  list_page:
    link_selectors:
      - css: ".gallery-item a"
    pagination:
      next_css: ".pagination .next"
  profile_page:
    fields: *default_fields

event_venue:
  list_page:
    link_selectors:
      - css: ".gallery-item a"
    pagination:
      next_css: ".pagination .next"
  profile_page:
    fields: *default_fields

retreat_host:
  list_page:
    link_selectors:
      - css: ".gallery-item a"
    pagination:
      next_css: ".pagination .next"
  profile_page:
    fields: *default_fields

press_outreach:
  list_page:
    link_selectors:
      - css: ".gallery-item a"
    pagination:
      next_css: ".pagination .next"
  profile_page:
    fields: *default_fields

corporate_wellness:
  list_page:
    link_selectors:
      - css: ".gallery-item a"
    pagination:
      next_css: ".pagination .next"
  profile_page:
    fields: *default_fields

podcast_host:
  list_page:
    link_selectors:
      - css: ".gallery-item a"
    pagination:
      next_css: ".pagination .next"
  profile_page:
    fields: *default_fields

nonprofit_partner:
  list_page:
    link_selectors:
      - css: ".gallery-item a"
    pagination:
      next_css: ".pagination .next"
  profile_page:
    fields: *default_fields

school_director:
  list_page:
    link_selectors:
      - css: ".gallery-item a"
    pagination:
      next_css: ".pagination .next"
  profile_page:
    fields: *default_fields

donor_aligned_leads:
  list_page:
    link_selectors:
      - css: ".gallery-item a"
    pagination:
      next_css: ".pagination .next"
  profile_page:
    fields: *default_fields